# Generated by Django 5.2.4 on 2025-08-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('text', 'Text/Notes'), ('slide', 'Slide Presentation')], max_length=20),
        ),
    ]
