# Generated by Django 5.2.4 on 2025-08-06 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_enrollment_completed_at_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of attempts allowed for this quiz.'),
        ),
        migrations.AddField(
            model_name='studentquizattempt',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts_for_enrollment', to='lmsApp.enrollment'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('text', 'Text/Notes'), ('slide', 'Slide Presentation'), ('quiz', 'Quiz'), ('assignment', 'Assignment')], max_length=20),
        ),
    ]
