# Generated by Django 5.2.4 on 2025-11-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0002_alter_content_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Upload a square image file for the course thumbnail.', null=True, upload_to='course_thumbnails/'),
        ),
    ]
