# Generated by Django 5.2.4 on 2025-08-06 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0003_quiz_max_attempts_studentquizattempt_enrollment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.OneToOneField(blank=True, help_text='The course this quiz is the main assessment for.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lmsApp.course'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('text', 'Text/Notes'), ('slide', 'Slide Presentation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Informational: suggested time limit in minutes.'),
        ),
    ]
