# Generated by Django 5.2.4 on 2025-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0004_remove_quiz_lesson_quiz_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Informational: suggested time limit in minutes.', null=True),
        ),
    ]
