# Generated by Django 5.2.4 on 2025-08-06 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0005_alter_quiz_duration_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='duration_minutes',
        ),
    ]
