# Generated by Django 5.2.4 on 2025-11-26 15:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0006_user_is_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
