# Generated by Django 5.2.4 on 2025-11-26 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0007_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='has_completed_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_relevance_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='1. Relevance to Career Growth')),
                ('course_quality_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='2. Course Content Quality')),
                ('instructor_effectiveness_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='3. Instructor Effectiveness')),
                ('course_structure_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='4. Course Structure & Organization')),
                ('actionable_feedback', models.TextField(verbose_name='5. How will you apply this learning to your job role?')),
                ('liked_most', models.TextField(blank=True, null=True, verbose_name='6. What did you like most?')),
                ('improvement_suggestions', models.TextField(blank=True, null=True, verbose_name='7. Suggestions for Improvement')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='lmsApp.enrollment')),
            ],
        ),
    ]
