# Generated by Django 5.2.4 on 2025-08-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0007_quiz_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total estimated duration of the course in minutes.'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Total estimated duration of the course in minutes.'),
        ),
    ]
