# Generated by Django 5.2.4 on 2025-11-26 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0008_enrollment_has_completed_survey_courseevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_student', True), _negated=True), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_enrollments', to=settings.AUTH_USER_MODEL),
        ),
    ]
