# Generated by Django 5.2.4 on 2025-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0009_enrollment_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
