# Generated by Django 5.2.4 on 2025-08-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0010_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='resolution_note',
            field=models.TextField(default='', verbose_name='Resolution Note'),
            preserve_default=False,
        ),
    ]
