# Generated by Django 5.2.4 on 2025-11-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0010_enrollment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='default_duration_days',
            field=models.IntegerField(default=30, help_text='Default days allowed for a student to complete this course.'),
        ),
    ]
