# Generated by Django 5.2.4 on 2025-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0011_alter_supportticket_resolution_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_id',
            field=models.CharField(default='', help_text='A unique, automatically generated ticket identifier.', max_length=8, unique=True, verbose_name='Ticket ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolution_note',
            field=models.TextField(blank=True, null=True, verbose_name='Resolution Note'),
        ),
    ]
