# Generated by Django 5.2.4 on 2025-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0012_supportticket_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('expert', 'Expert'), ('professional', 'Professional')], default='beginner', max_length=20),
        ),
    ]
