# Generated by Django 5.2.4 on 2026-07-30 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0012_alter_supportticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='diagram_code',
            field=models.TextField(blank=True, help_text='Mermaid.js syntax for a generated conceptual diagram (flowchart, sequence, hierarchy). Rendered client-side with mermaid.js; not a raster image.', null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, help_text='Image extracted directly from the source PDF page.', null=True, upload_to='lms_content_images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='source_page_number',
            field=models.PositiveIntegerField(blank=True, help_text='Page in the source PDF this content was derived from, for traceability back to the original document.', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF Document'), ('text', 'Text/Notes'), ('slide', 'Slide Presentation'), ('image', 'Image/Diagram (extracted)'), ('diagram', 'Generated Diagram (Mermaid)')], max_length=20),
        ),
        migrations.CreateModel(
            name='CourseImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='course_imports/source_pdfs/')),
                ('custom_title', models.CharField(blank=True, max_length=200, null=True)),
                ('generate_quiz', models.BooleanField(default=True)),
                ('requested_min_questions', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('extracting_text', 'Extracting Text'), ('extracting_images', 'Extracting Images'), ('generating_outline', 'Generating Course Outline'), ('generating_content', 'Generating Lesson Content'), ('generating_quiz', 'Generating Quiz Questions'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('pages_processed', models.PositiveIntegerField(default=0)),
                ('images_extracted', models.PositiveIntegerField(default=0)),
                ('questions_generated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_job', to='lmsApp.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
