# Generated by Django 5.2.4 on 2026-08-08 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0013_content_diagram_code_content_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly_usage', 'Monthly Platform Usage Report')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_emails', models.TextField(help_text='Comma-separated list of recipients.')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assignment_reason',
            field=models.CharField(choices=[('self', 'Self-Enrolled'), ('manual', 'Manually Assigned'), ('bulk_department', 'Bulk Assigned by Department')], default='self', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='followup_2mo_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='followup_3mo_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reminder_3_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='reminder_7_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.OneToOneField(blank=True, help_text="Set only when quiz_type='module_check'. The module this knowledge check belongs to.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lmsApp.module'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('final', 'Final Course Assessment'), ('module_check', 'Module Knowledge Check')], default='final', max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.OneToOneField(blank=True, help_text="Set only when quiz_type='final'. The course this quiz is the main assessment for.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='lmsApp.course'),
        ),
        migrations.CreateModel(
            name='ExternalTrainingResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('ms_learn', 'Microsoft Learn'), ('cisco', 'Cisco'), ('sophos', 'Sophos'), ('linkedin_learning', 'LinkedIn Learning'), ('coursera', 'Coursera'), ('other', 'Other')], default='ms_learn', max_length=30)),
                ('source', models.CharField(choices=[('synced', 'Auto-Synced'), ('manual', 'Manually Curated')], default='manual', max_length=10)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('external_uid', models.CharField(blank=True, help_text="The provider's own content ID (e.g. MS Learn module UID). Used to dedupe on re-sync.", max_length=255, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('product_area', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='external_resources', to='lmsApp.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTrainingCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='external_training_proofs/')),
                ('verified', models.BooleanField(default=False)),
                ('student', models.ForeignKey(limit_choices_to={'is_student': True}, on_delete=django.db.models.deletion.CASCADE, related_name='external_training_completions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_completions_verified', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='lmsApp.externaltrainingresource')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_title', models.CharField(blank=True, max_length=255, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='instructor_training_proofs/')),
                ('completion_note', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_trainings', to='lmsApp.course')),
                ('instructor', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='externaltrainingresource',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'synced')), fields=('provider', 'external_uid'), name='unique_synced_external_resource'),
        ),
        migrations.AlterUniqueTogether(
            name='externaltrainingcompletion',
            unique_together={('student', 'resource')},
        ),
    ]
