# Generated by Django 5.2.4 on 2025-08-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0013_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='assessment_status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Not Attempted', 'Not Attempted')], default='Not Attempted', max_length=50),
        ),
    ]
