# Generated by Django 5.2.4 on 2026-08-09 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0014_reportlog_enrollment_assignment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_origin',
            field=models.CharField(choices=[('manual', 'Manually Authored'), ('pdf_generated', 'AI-Generated from PDF'), ('external_resource_curated', 'AI-Curated from External Resource')], default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='source_external_resources',
            field=models.ManyToManyField(blank=True, help_text='Resource(s) used as reference material. Provenance only — not a live sync.', related_name='curated_courses', to='lmsApp.externaltrainingresource'),
        ),
        migrations.AlterField(
            model_name='courseimportjob',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_import_jobs', to='lmsApp.course'),
        ),
        migrations.CreateModel(
            name='ExternalResourceImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('generate_quiz', models.BooleanField(default=True, help_text='Generate a final course assessment.')),
                ('generate_module_quizzes', models.BooleanField(default=False, help_text='Also generate a knowledge check per module (only used in multi-resource mode).')),
                ('requested_min_questions', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating_outline', 'Generating Outline'), ('generating_content', 'Generating Content'), ('generating_quiz', 'Generating Quiz'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('questions_generated', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_resource_import_jobs', to='lmsApp.course')),
                ('external_resources', models.ManyToManyField(help_text='One resource → AI designs its own module breakdown. Multiple resources → one module generated per resource, in order.', related_name='import_jobs', to='lmsApp.externaltrainingresource')),
                ('instructor', models.ForeignKey(limit_choices_to={'is_instructor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='external_resource_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
