# Generated by Django 5.2.4 on 2025-08-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0014_enrollment_assessment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='assessment_status',
        ),
    ]
