# Generated by Django 5.2.4 on 2025-08-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0015_remove_enrollment_assessment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_multiple_correct',
            field=models.BooleanField(default=False),
        ),
    ]
