# Generated by Django 5.2.4 on 2026-08-11 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0015_course_content_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, help_text="Optional grouping, e.g. 'Technical', 'Leadership', 'Compliance'.", max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Competencies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CourseCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.PositiveSmallIntegerField(choices=[(1, 'Foundational'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lmsApp.competency')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_competencies', to='lmsApp.course')),
            ],
            options={
                'unique_together': {('course', 'competency')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency_level', models.PositiveSmallIntegerField(choices=[(1, 'Foundational'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Expert')], default=1)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_records', to='lmsApp.competency')),
                ('source_course', models.ForeignKey(blank=True, help_text='The course that most recently drove this competency to its current level.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsApp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Competencies',
                'unique_together': {('user', 'competency')},
            },
        ),
    ]
