# Generated by Django 5.2.4 on 2025-08-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0016_quiz_allow_multiple_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='chosen_option',
        ),
        migrations.AddField(
            model_name='question',
            name='is_multi_select',
            field=models.BooleanField(default=False, help_text='Check if this question allows multiple correct answers.'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='chosen_options',
            field=models.ManyToManyField(blank=True, related_name='chosen_by_students', to='lmsApp.option'),
        ),
    ]
