# Generated by Django 5.2.4 on 2026-08-12 14:56

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsApp', '0016_competency_coursecompetency_employeecompetency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True),
        ),
    ]
